### PR TITLE
Fix `torch.dtype` checks in `to` tests

### LINKED ISSUE #333: `to` tests fail with torch 2.0.0
With torch 2.0.0, the `to` tests fail with the following errors:
```
FAILED to.py::test_numpy_to_torch_gpu_block - AttributeError: 'TensorBlock' object has no attribute 'device'
FAILED to.py::test_torch_to_gpu_block - AttributeError: 'torch.device' object has no attribute 'is_cuda'
```

### PR DESCRIPTION
**Pull request by frostedoyster**
Fixes #333.

----
:books: Documentation preview :books:: https://equistore--334.org.readthedocs.build/en/334/

### CODE REVIEW

**Comment by Luthaf** [comment]
Since we don't run the CUDA tests on CI, could you check if this code also works with torch 1.11 (our oldest supported version)? Otherwise everything looks good.
